import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';import {Hono} from 'hono';import {albumMediaRoutes,publicAlbumPhoto} from '../src/album-media.js';
test('shared album photos migrate, stay unique, have independent notes and retain originals',async()=>{
 const db=new DatabaseSync(':memory:');db.exec("PRAGMA foreign_keys=ON;CREATE TABLE entries(id TEXT PRIMARY KEY,kind TEXT,status TEXT,cover TEXT DEFAULT '',updated_at TEXT);CREATE TABLE media(id TEXT PRIMARY KEY,entry_id TEXT,caption TEXT,position INTEGER,created_at TEXT);INSERT INTO entries(id,kind,status) VALUES('a','album','draft'),('b','album','published'),('c','blog','published');INSERT INTO media VALUES('p','a','original note',1,'2026-10-05');");db.exec(readFileSync(new URL('../migrations/0018_shared_album_photos.sql',import.meta.url),'utf8'));
 const DB={prepare(sql){return {bind(...args){const statement=db.prepare(sql);return {async first(){return statement.get(...args)},async all(){return {results:statement.all(...args)}},async run(){return statement.run(...args)}};}};},async batch(statements){return Promise.all(statements.map(s=>s.run()));}};
 const app=new Hono();albumMediaRoutes(app);const req=async(path,method,body)=>app.fetch(new Request('https://example.com/api/admin/albums/'+path,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}),{DB});
 assert.equal(db.prepare('SELECT COUNT(*) AS n FROM album_media').get().n,1);assert.equal(await publicAlbumPhoto({env:{DB}},'p'),false);
 assert.equal((await req('b/photos','POST',{ids:['p','p']})).status,200);await req('b/photos','POST',{ids:['p']});assert.equal(db.prepare('SELECT COUNT(*) AS n FROM album_media').get().n,2);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM media').get().n,1);assert.equal(await publicAlbumPhoto({env:{DB}},'p'),true);
 await req('b/photos/p','PUT',{caption:'second note'});assert.equal(db.prepare("SELECT caption FROM album_media WHERE album_id='a'").get().caption,'original note');assert.equal(db.prepare("SELECT caption FROM album_media WHERE album_id='b'").get().caption,'second note');
 assert.equal((await req('c/photos','POST',{ids:['p']})).status,404);assert.equal((await req('b/photos','POST',{ids:['missing']})).status,409);
 await req('b/photos/p','DELETE');assert.equal(await publicAlbumPhoto({env:{DB}},'p'),false);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM media').get().n,1);
 await req('a/photos/p','DELETE');assert.equal(db.prepare('SELECT COUNT(*) AS n FROM album_media').get().n,0);assert.equal((await req('b/photos','POST',{ids:['p']})).status,200);assert.equal(await publicAlbumPhoto({env:{DB}},'p'),true);
 db.prepare("DELETE FROM media WHERE id='p'").run();assert.equal(db.prepare('SELECT COUNT(*) AS n FROM album_media').get().n,0);db.close();
});
