import assert from 'node:assert/strict';
const origin='http://127.0.0.1:8787';let cookie='';
async function call(path,body,admin=false,method=body?'POST':'GET',extra={}){const headers={Origin:origin,...(body&&!(body instanceof FormData)?{'Content-Type':'application/json'}:{}),...(admin?{Cookie:cookie}:{}),...extra};const r=await fetch(origin+path,{method,headers,body:body instanceof FormData?body:body?JSON.stringify(body):undefined});const b=r.headers.get('content-type')?.includes('json')?await r.json():await r.text();return {r,b}}
let auth=await call('/api/auth/status');if(!auth.b.initialized){const setup=await call('/api/auth/setup',{token:'local-testing-only-not-for-production',password:'local-test-password-98765'});assert.equal(setup.r.status,200);cookie=setup.r.headers.get('set-cookie').split(';')[0]}else{const login=await call('/api/auth/login',{email:(process.env.TEST_ADMIN_EMAIL||'admin@example.com'),password:'local-test-password-98765'});assert.equal(login.r.status,200);cookie=login.r.headers.get('set-cookie').split(';')[0]}
assert.equal((await call('/api/admin/entries')).r.status,401);
const csrf=await call('/api/admin/entries',{kind:'blog',title:'attack'},true,'POST',{Origin:'https://evil.test'});assert.equal(csrf.r.status,403);
const created=await call('/api/admin/entries',{kind:'blog',title:'PRIVATE-TEST',body:'<p>private-body-987</p><script>alert(1)</script>',excerpt:'private-excerpt',date:'2026-09-18',status:'published',password:'test-lock'},true);assert.equal(created.r.status,200);const id=created.b.id;
const list=await call('/api/entries?kind=blog');const card=list.b.items.find(x=>x.id===id);assert.equal(card.excerpt,'');assert.equal(card.locked,true);assert.equal(JSON.stringify(list.b).includes('private-body'),false);
const locked=await call('/api/entries/'+id);assert.equal(locked.r.status,423);assert.equal(JSON.stringify(locked.b).includes('private-body'),false);
assert.equal((await call('/api/entries/'+id+'/unlock',{password:'wrong'})).r.status,403);
const unlocked=await call('/api/entries/'+id+'/unlock',{password:'test-lock'});assert.equal(unlocked.r.status,200);assert.match(unlocked.b.entry.body,/private-body/);assert.doesNotMatch(unlocked.b.entry.body,/script/);const access={'X-Article-Token':unlocked.b.token};assert.equal((await call('/api/entries/'+id,null,false,'GET',access)).r.status,200);
assert.equal((await call('/api/comments?entry='+id)).r.status,403);
const comment=await call('/api/comments',{entry_id:null,nickname:'Integration Visitor',email:'test@example.com',message:'待审核的测试留言'});assert.equal(comment.r.status,200);assert.equal((await call('/api/comments')).b.some(x=>x.nickname==='Integration Visitor'),false);
const mod=await call('/api/admin/comments',null,true);const commentId=mod.b.find(x=>x.nickname==='Integration Visitor').id;await call('/api/admin/comments/'+commentId,{status:'approved',reply:'回复测试'},true,'PUT');const published=await call('/api/comments');assert.equal(published.b.some(x=>x.id===commentId),true);assert.equal(JSON.stringify(published.b).includes('test@example.com'),false);
const act=await call('/api/admin/activities',{name:'PRIVATE ACTIVITY',icon:'🌱',private:true,color:'#123456'},true);assert.equal(act.r.status,200);const day='2026-09-01';await call('/api/admin/checkins',{activity_id:act.b.id,date:day},true);await call('/api/admin/checkins',{activity_id:act.b.id,date:day},true);const publicLife=await call('/api/life?year=2026');assert.equal(JSON.stringify(publicLife.b).includes(act.b.id),false);const privateLife=await call('/api/life?year=2026',null,true);assert.equal(privateLife.b.checks.filter(x=>x.activity_id===act.b.id).length,1);assert.equal((await call('/api/admin/checkins',{activity_id:act.b.id,date:'2099-01-01'},true)).r.status,400);
const fd=new FormData();fd.set('file',new Blob([Uint8Array.from([137,80,78,71,13,10,26,10])],{type:'image/png'}),'test.png');fd.set('entry_id',id);const upload=await call('/api/admin/media',fd,true);assert.equal(upload.r.status,200);assert.equal((await call(upload.b.url)).r.status,403);assert.equal((await call(upload.b.url,null,false,'GET',access)).r.status,200);
await call('/api/admin/entries/'+id,{kind:'blog',title:'PRIVATE-TEST',body:'<p>changed</p>',date:'2026-09-18',status:'published',password:'new-lock'},true,'PUT');assert.equal((await call('/api/entries/'+id,null,false,'GET',access)).r.status,423);
await call('/api/admin/entries/'+id+'/archive',{},true);assert.equal((await call('/api/entries/'+id)).r.status,404);assert.equal((await call(upload.b.url,null,false,'GET',access)).r.status,403);
await call('/api/admin/comments/'+commentId,{status:'rejected'},true,'PUT');
const bangumi=await call('/api/bangumi/collections?type=3');assert.equal(bangumi.r.status,200);assert.ok(Array.isArray(bangumi.b.data.data));
console.log('PASS: admin auth, CSRF, locked metadata/body/media, scoped unlock expiry on edit, drafts, moderation, email privacy, private activities, idempotent checkins, date validation, Bangumi');
