CREATE TABLE games(id TEXT PRIMARY KEY,bgm_id INTEGER,title TEXT NOT NULL,cover TEXT NOT NULL DEFAULT '',summary TEXT NOT NULL DEFAULT '',review TEXT NOT NULL DEFAULT '',steam_appid INTEGER,status TEXT NOT NULL DEFAULT 'draft',updated_at TEXT NOT NULL);
CREATE TABLE steam_games(appid INTEGER PRIMARY KEY,name TEXT NOT NULL,minutes INTEGER NOT NULL,synced_at TEXT NOT NULL);
CREATE TABLE game_secrets(key TEXT PRIMARY KEY,value TEXT NOT NULL);
