import {plain} from './security.js';
const steamID='76561198976757811';
const image=v=>/^https:\/\/lain\.bgm\.tv\//.test(String(v))?String(v):'';
const q=(c,s,...a)=>c.env.DB.prepare(s).bind(...a);
async function secret(c,key){return (await q(c,'SELECT value FROM game_secrets WHERE key=?',key).first())?.value}
async function setSecret(c,key,value){await q(c,'INSERT INTO game_secrets(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value',key,value).run()}
export function parseSteamGames(data){if(!Array.isArray(data?.response?.games))throw Error('无法读取 Steam 游戏时长，请检查密钥，并将 Steam「游戏详情」设为公开、关闭总游玩时间保密。');return data.response.games.filter(g=>Number.isSafeInteger(g.appid)&&g.appid>0&&Number.isFinite(g.playtime_forever)&&g.playtime_forever>=0).map(g=>({appid:g.appid,name:String(g.name||g.appid),minutes:Math.floor(g.playtime_forever)}))}
async function syncSteam(c,force=false){const key=await secret(c,'steam-key');if(!key){if(force)throw Error('请先配置 Steam Web API Key。');return}const claim=await q(c,"INSERT INTO game_secrets(key,value) VALUES('attempt',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value WHERE CAST(game_secrets.value AS INTEGER)<? RETURNING key",String(Date.now()),Date.now()-(force?60000:3600000)).first();if(!claim){if(force)throw Error('刚刚同步过，请一分钟后再试。');return}try{const u=new URL('https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/');u.search=new URLSearchParams({key,steamid:steamID,include_appinfo:'1',include_played_free_games:'1',format:'json'});const r=await fetch(u,{signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error('Steam 同步失败，请检查密钥及账号隐私设置。');const games=parseSteamGames(await r.json()),now=new Date().toISOString();const statements=[q(c,'DELETE FROM steam_games'),...games.map(g=>q(c,'INSERT INTO steam_games(appid,name,minutes,synced_at) VALUES(?,?,?,?)',g.appid,g.name,g.minutes,now))];await c.env.DB.batch(statements);await setSecret(c,'synced',now);await setSecret(c,'error','')}catch(e){const msg=e.message?.startsWith('无法读取')||e.message?.startsWith('Steam 同步失败')?e.message:'Steam 暂时无法连接，已保留上次同步数据。';await setSecret(c,'error',msg);if(force)throw Error(msg)}}
export function gameRoutes(app){
 app.get('/api/games',async c=>{c.executionCtx.waitUntil(syncSteam(c).catch(()=>{}));const limit=c.req.query('home')==='1'?3:200;return c.json((await q(c,"SELECT g.*,s.minutes,s.synced_at FROM games g LEFT JOIN steam_games s ON g.steam_appid=s.appid WHERE g.status='published' ORDER BY g.updated_at DESC,g.id LIMIT ?",limit).all()).results)});
 app.get('/api/admin/games',async c=>c.json({games:(await q(c,'SELECT * FROM games ORDER BY updated_at DESC').all()).results,steam:(await q(c,'SELECT * FROM steam_games ORDER BY minutes DESC').all()).results,configured:!!await secret(c,'steam-key'),synced:await secret(c,'synced')||'',error:await secret(c,'error')||''}));
 app.get('/api/admin/games/search',async c=>{const keyword=String(c.req.query('q')||'').trim().slice(0,100);if(!keyword)return c.json([]);try{const r=await fetch('https://api.bgm.tv/v0/search/subjects?limit=12',{method:'POST',headers:{'Content-Type':'application/json','User-Agent':'mingdizhiying/lsfw (https://lsfw.top)'},body:JSON.stringify({keyword,filter:{type:[4],nsfw:false}}),signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error();const d=await r.json();return c.json((d.data||[]).filter(x=>x.type===4).map(x=>({bgm_id:x.id,title:x.name_cn||x.name,cover:image(x.images?.large||x.image),summary:x.summary||''})))}catch{return c.json({error:'Bangumi 搜索暂时不可用，请稍后重试。'},502)}});
 app.put('/api/admin/games/steam-key',async c=>{const {key}=await c.req.json();if(typeof key!=='string'||!/^([a-f\d]{32})?$/i.test(key))return c.json({error:'请填写有效的 32 位 Steam API Key，或留空移除。'},400);await setSecret(c,'steam-key',key);await setSecret(c,'attempt','0');return c.json({ok:true})});
 app.post('/api/admin/games/sync',async c=>{try{await syncSteam(c,true);return c.json({ok:true})}catch(e){return c.json({error:e.message},400)}});
 app.put('/api/admin/games/:id',async c=>{const b=await c.req.json(),id=c.req.param('id'),appid=b.steam_appid?Number(b.steam_appid):null,bgm=b.bgm_id?Number(b.bgm_id):null;if(!/^[a-z\d-]{1,80}$/i.test(id)||!plain(b.title)||appid!==null&&(!Number.isSafeInteger(appid)||appid<1)||bgm!==null&&(!Number.isSafeInteger(bgm)||bgm<1)||b.cover&&!image(b.cover))return c.json({error:'请检查游戏名称、封面和 Steam App ID。'},400);await q(c,'INSERT INTO games(id,bgm_id,title,cover,summary,review,steam_appid,status,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET bgm_id=excluded.bgm_id,title=excluded.title,cover=excluded.cover,summary=excluded.summary,review=excluded.review,steam_appid=excluded.steam_appid,status=excluded.status,updated_at=excluded.updated_at',id,bgm,plain(b.title).slice(0,200),image(b.cover),String(b.summary||'').slice(0,20000),String(b.review||'').slice(0,3000),appid,b.status==='published'?'published':'draft',new Date().toISOString()).run();return c.json({id})});
}
