import {plain,validDate,today} from './security.js';
export function poetryRoutes(app){
  const q=(c,s,...args)=>c.env.DB.prepare(s).bind(...args);
  app.get('/api/poetry/poems',async c=>{const offset=Math.max(0,Math.min(100000,Math.floor(Number(c.req.query('offset'))||0)));const rows=(await q(c,"SELECT p.id,p.title,p.date,p.book_id,b.title AS book_title FROM poems p JOIN poetry_books b ON p.book_id=b.id WHERE p.status='published' AND b.status='published' ORDER BY p.date DESC,b.position,p.position,p.id LIMIT 30 OFFSET ?",offset).all()).results;const total=(await q(c,"SELECT COUNT(*) AS n FROM poems p JOIN poetry_books b ON p.book_id=b.id WHERE p.status='published' AND b.status='published'").first()).n;return c.json({items:rows,total})});
  app.get('/api/poetry',async c=>c.json((await q(c,"SELECT b.id,b.title,b.description,b.cover,b.date,b.position,COUNT(p.id) AS count FROM poetry_books b LEFT JOIN poems p ON p.book_id=b.id AND p.status='published' WHERE b.status='published' GROUP BY b.id ORDER BY b.position,b.created_at").all()).results));
  app.get('/api/poetry/books/:id',async c=>{const book=await q(c,"SELECT id,title,description,cover,date FROM poetry_books WHERE id=? AND status='published'",c.req.param('id')).first();if(!book)return c.json({error:'诗集尚未公开。'},404);return c.json({...book,poems:(await q(c,"SELECT id,title,date FROM poems WHERE book_id=? AND status='published' ORDER BY position,date,id",book.id).all()).results})});
  app.get('/api/poetry/poems/:id',async c=>{const poem=await q(c,"SELECT p.*,b.title AS book_title FROM poems p JOIN poetry_books b ON p.book_id=b.id WHERE p.id=? AND p.status='published' AND b.status='published'",c.req.param('id')).first();return poem?c.json(poem):c.json({error:'这首诗尚未公开。'},404)});
  app.get('/api/admin/poetry',async c=>c.json({books:(await q(c,'SELECT * FROM poetry_books ORDER BY position,created_at').all()).results,poems:(await q(c,'SELECT * FROM poems ORDER BY position,date,id').all()).results}));
  app.put('/api/admin/poetry/books/:id',async c=>{const b=await c.req.json(),id=c.req.param('id'),old=await q(c,'SELECT * FROM poetry_books WHERE id=?',c.req.param('id')).first(),date=b.date??old?.date??today(),cover=b.cover??old?.cover??'';if(!/^[a-z\d-]{1,80}$/i.test(id)||!plain(b.title)||!validDate(date))return c.json({error:'请填写诗集名称和有效日期。'},400);if(cover&&(!/^\/media\/[a-z\d-]+$/i.test(cover)||!await q(c,'SELECT id FROM media WHERE id=? AND entry_id IS NULL',cover.slice(7)).first()))return c.json({error:'请上传有效的诗集封面。'},400);await q(c,'INSERT INTO poetry_books(id,title,description,status,position,created_at,cover,date) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,description=excluded.description,status=excluded.status,position=excluded.position,cover=excluded.cover,date=excluded.date',id,plain(b.title).slice(0,160),String(b.description||'').slice(0,3000),b.status==='published'?'published':'draft',Number.isSafeInteger(Number(b.position))?Number(b.position):0,new Date().toISOString(),cover,date).run();return c.json({id})});
  app.put('/api/admin/poetry/poems/:id',async c=>{const b=await c.req.json(),id=c.req.param('id');if(!/^[a-z\d-]{1,80}$/i.test(id)||!plain(b.title)||!validDate(b.date||today())||String(b.body||'').length>50000)return c.json({error:'请检查诗题、日期与正文长度。'},400);if(!await q(c,'SELECT id FROM poetry_books WHERE id=?',b.book_id).first())return c.json({error:'请先创建诗集。'},400);await q(c,'INSERT INTO poems(id,book_id,title,body,date,status,position,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET book_id=excluded.book_id,title=excluded.title,body=excluded.body,date=excluded.date,status=excluded.status,position=excluded.position,updated_at=excluded.updated_at',id,b.book_id,plain(b.title).slice(0,160),String(b.body||''),b.date||today(),b.status==='published'?'published':'draft',Number.isSafeInteger(Number(b.position))?Number(b.position):0,new Date().toISOString()).run();return c.json({id})});
}
