import {defaultHomeCopy} from '../public/home-copy.js';
import {poetryRoutes} from './poetry.js';
import {foodRoutes} from './food.js';
import {deleteMedia} from './media-delete.js';
import { Hono } from 'hono';
import { getCookie,setCookie,deleteCookie } from 'hono/cookie';
import {clean,plain,random,digest,hashPassword,verifyPassword,constantEqual,today,validDate,emailValid,safeLink} from './security.js';
const app=new Hono();
const defaults={name:'岚山飞文',nickname:'飞文',intro:'把日子过成故事，\n把喜欢的瞬间留在这里。',bio:'一些照片，一些文字，还有慢慢完成的小事。\n欢迎翻翻我的生活手记。',tags:['摄影','阅读','动漫','记录生活'],avatar:'',email:'',socials:[]};
const now=()=>new Date().toISOString();
const query=(c,s,...p)=>c.env.DB.prepare(s).bind(...p);
const all=async(c,s,...p)=>(await query(c,s,...p).all()).results;
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status})};
const data=async c=>{try{return await c.req.json()}catch{fail('提交的数据无法读取')}};
async function profile(c){const row=await query(c,"SELECT value FROM settings WHERE key='profile'").first();return row?{...defaults,...JSON.parse(row.value)}:defaults}
async function isAdmin(c){const t=getCookie(c,'lsfw_session');return !!(t&&await query(c,'SELECT token_hash FROM sessions WHERE token_hash=? AND expires_at>?',await digest(t),Date.now()).first())}
async function rate(c,key,max=10,window=600000){const ip=c.req.header('CF-Connecting-IP')||'local';const k=await digest(key+':'+ip);const row=await query(c,'INSERT INTO limits(key,hits,expires_at) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET hits=CASE WHEN limits.expires_at<? THEN 1 ELSE hits+1 END,expires_at=CASE WHEN limits.expires_at<? THEN excluded.expires_at ELSE limits.expires_at END RETURNING hits',k,Date.now()+window,Date.now(),Date.now()).first();if(row.hits>max)fail('操作太频繁，请稍后再试。',429)}
async function login(c){const token=random();await query(c,'INSERT INTO sessions(token_hash,expires_at) VALUES(?,?)',await digest(token),Date.now()+7*86400000).run();setCookie(c,'lsfw_session',token,{httpOnly:true,secure:new URL(c.req.url).protocol==='https:',sameSite:'Strict',path:'/',maxAge:7*86400});return c.json({ok:true})}
app.use('*',async(c,next)=>{
 const pathname=new URL(c.req.url).pathname;
 if(!['GET','HEAD','OPTIONS'].includes(c.req.method)){
  const origin=c.req.header('Origin');if(origin!==new URL(c.req.url).origin)fail('请求来源无效。',403);
  if(Number(c.req.header('Content-Length')||0)>9*1024*1024)fail('文件过大。',413);
 }
 await next();
 c.header('X-Content-Type-Options','nosniff');c.header('Referrer-Policy','strict-origin-when-cross-origin');c.header('X-Frame-Options','DENY');
 c.header('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob: https://lain.bgm.tv; connect-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'; object-src 'none'");
 if(pathname.startsWith('/api/')||pathname.startsWith('/admin')||pathname.startsWith('/media/'))c.header('Cache-Control','no-store');
});
app.onError((err,c)=>{console.error('Request failed',c.req.path,err.status||500);return c.json({error:err.status?err.message:'暂时无法完成操作，请稍后重试。'},err.status||500)});
app.get('/api/profile',async c=>c.json(await profile(c)));
app.get('/api/auth/status',async c=>c.json({authenticated:await isAdmin(c),initialized:!!(await query(c,'SELECT id FROM admin WHERE id=1').first())}));
app.post('/api/auth/setup',async c=>{await rate(c,'setup',5);const b=await data(c);if(!c.env.SETUP_TOKEN||!constantEqual(b.token,c.env.SETUP_TOKEN))fail('初始化密钥不正确。',403);if(await query(c,'SELECT id FROM admin WHERE id=1').first())fail('管理员已经设置完成。',409);if(typeof b.password!=='string'||b.password.length<12||b.password.length>128)fail('管理密码须为12–128个字符。');await query(c,'INSERT INTO admin(id,email,password_hash,created_at) VALUES(1,?,?,?)',c.env.ADMIN_EMAIL.toLowerCase(),await hashPassword(b.password),now()).run();return login(c)});
app.post('/api/auth/login',async c=>{await rate(c,'login',8);const b=await data(c);const a=await query(c,'SELECT * FROM admin WHERE id=1').first();const valid=await verifyPassword(b.password,a?.password_hash||`${'0'.repeat(64)}:${'0'.repeat(64)}`);if(!a||String(b.email).toLowerCase()!==a.email||!valid)fail('邮箱或密码不正确。',401);return login(c)});
app.post('/api/auth/logout',async c=>{const t=getCookie(c,'lsfw_session');if(t)await query(c,'DELETE FROM sessions WHERE token_hash=?',await digest(t)).run();deleteCookie(c,'lsfw_session',{path:'/'});return c.json({ok:true})});
app.use('/api/admin/*',async(c,next)=>{if(!await isAdmin(c))fail('请先登录后台。',401);await next()});

app.get('/api/home-copy',async c=>{const r=await query(c,"SELECT value FROM settings WHERE key='home-copy'").first();return c.json({...defaultHomeCopy,...(r?JSON.parse(r.value):{})})});
app.put('/api/admin/home-copy',async c=>{const b=await data(c),out={};for(const key of Object.keys(defaultHomeCopy))out[key]=typeof b[key]==='string'?b[key].slice(0,2000):defaultHomeCopy[key];await query(c,"INSERT INTO settings(key,value) VALUES('home-copy',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",JSON.stringify(out)).run();return c.json({ok:true})});
poetryRoutes(app);
foodRoutes(app);
app.get('/api/admin/overview',async c=>c.json({counts:await all(c,'SELECT kind,status,COUNT(*) AS count FROM entries GROUP BY kind,status'),pending:(await query(c,"SELECT COUNT(*) AS n FROM comments WHERE status='pending'").first()).n,mailConfigured:!!(c.env.RESEND_API_KEY&&c.env.MAIL_FROM),mailPending:(await query(c,"SELECT COUNT(*) AS n FROM mail_outbox WHERE status='pending'").first()).n,storageReady:!!c.env.MEDIA,email:c.env.ADMIN_EMAIL}));
app.put('/api/admin/profile',async c=>{const b=await data(c);const p={name:plain(b.name).slice(0,40)||defaults.name,nickname:plain(b.nickname).slice(0,30)||'飞文',intro:plain(b.intro).slice(0,300),bio:plain(b.bio).slice(0,2000),tags:(Array.isArray(b.tags)?b.tags:[]).slice(0,12).map(x=>plain(x).slice(0,20)),avatar:/^\/media\/[a-zA-Z0-9-]+$/.test(b.avatar)?b.avatar:'',email:b.email&&emailValid(b.email)?b.email:'',socials:(Array.isArray(b.socials)?b.socials:[]).slice(0,10).map(s=>({name:plain(s.name).slice(0,30),url:safeLink(s.url)})).filter(s=>s.url)};await query(c,"INSERT INTO settings(key,value) VALUES('profile',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",JSON.stringify(p)).run();return c.json(p)});
app.post('/api/admin/password',async c=>{const b=await data(c);const a=await query(c,'SELECT password_hash FROM admin WHERE id=1').first();if(!await verifyPassword(b.current,a.password_hash))fail('当前密码不正确。');if(typeof b.password!=='string'||b.password.length<12||b.password.length>128)fail('新密码须为12–128个字符。');await c.env.DB.batch([query(c,'UPDATE admin SET password_hash=? WHERE id=1',await hashPassword(b.password)),query(c,'DELETE FROM sessions')]);return login(c)});
const summaryFields="id,kind,title,CASE WHEN password_hash IS NULL THEN excerpt ELSE '' END AS excerpt,CASE WHEN password_hash IS NULL THEN cover ELSE '' END AS cover,CASE WHEN password_hash IS NULL THEN tags ELSE '[]' END AS tags,date,status,password_hash IS NOT NULL AS locked,updated_at";
function pack(row){if(!row)return row;const r={...row,tags:JSON.parse(row.tags||'[]'),locked:!!(row.locked||row.password_hash)};delete r.password_hash;return r}
app.get('/api/entries',async c=>{const kind=c.req.query('kind')||'blog';if(!['blog','note','album','project'].includes(kind))fail('栏目不存在。',404);const limit=Math.min(30,Math.max(1,Number(c.req.query('limit'))||12)),offset=Math.max(0,Number(c.req.query('offset'))||0);const rows=await all(c,`SELECT ${summaryFields}${kind==='note'?',body':''} FROM entries WHERE kind=? AND status='published' ORDER BY date DESC,created_at DESC LIMIT ? OFFSET ?`,kind,limit,offset);const total=(await query(c,"SELECT COUNT(*) AS n FROM entries WHERE kind=? AND status='published'",kind).first()).n;return c.json({items:rows.map(pack),total,limit,offset})});
async function visibleEntry(c,id){const row=await query(c,"SELECT * FROM entries WHERE id=? AND status='published'",id).first();if(!row)fail('内容不存在或尚未发布。',404);return row}
async function entryAccess(c,entry){if(!entry.password_hash)return true;const token=c.req.header('X-Article-Token');if(!token)return false;const r=await query(c,"SELECT value FROM cache WHERE key=? AND expires_at>?",'unlock:'+await digest(token),Date.now()).first();return r&&JSON.parse(r.value).id===entry.id&&JSON.parse(r.value).version===entry.updated_at}
async function detail(c,entry){const photos=await all(c,'SELECT id,caption,position FROM media WHERE entry_id=? ORDER BY position,created_at',entry.id);return {...pack(entry),photos}}
app.get('/api/entries/:id',async c=>{const e=await visibleEntry(c,c.req.param('id'));if(!await entryAccess(c,e))return c.json({id:e.id,title:e.title,date:e.date,kind:e.kind,locked:true},423);return c.json(await detail(c,e))});
app.post('/api/entries/:id/unlock',async c=>{await rate(c,'unlock:'+c.req.param('id'),10);const e=await visibleEntry(c,c.req.param('id'));const b=await data(c);if(!e.password_hash)return c.json({entry:await detail(c,e)});if(!await verifyPassword(b.password,e.password_hash))fail('密码不正确。',403);const token=random();await query(c,'INSERT INTO cache(key,value,expires_at) VALUES(?,?,?)','unlock:'+await digest(token),JSON.stringify({id:e.id,version:e.updated_at}),Date.now()+2*3600000).run();return c.json({token,entry:await detail(c,e)})});
app.get('/api/admin/entries',async c=>c.json((await all(c,'SELECT id,kind,title,date,status,password_hash IS NOT NULL AS locked,updated_at FROM entries ORDER BY updated_at DESC LIMIT 500')).map(pack)));
app.get('/api/admin/entries/:id',async c=>{const e=await query(c,'SELECT * FROM entries WHERE id=?',c.req.param('id')).first();if(!e)fail('内容不存在。',404);return c.json(await detail(c,e))});
async function saveEntry(c){const b=await data(c),id=c.req.param('id')||crypto.randomUUID(),old=await query(c,'SELECT * FROM entries WHERE id=?',id).first();if(c.req.param('id')&&!old)fail('内容不存在。',404);const kind=old?.kind||b.kind;if(!['blog','note','project','album'].includes(kind))fail('请选择内容类型。');const title=plain(b.title).slice(0,160);if(!title&&kind!=='note')fail('请填写标题。');const body=clean(b.body);if(body.length>250000)fail('文章过长，请拆分后发布。');const date=b.date||today();if(!validDate(date))fail('日期格式不正确。');const status=b.status==='published'?'published':'draft';let ph=old?.password_hash||null;if(kind==='blog'){if(b.removePassword)ph=null;else if(b.password){if(typeof b.password!=='string'||b.password.length<4||b.password.length>128)fail('文章密码须为4–128个字符。');ph=await hashPassword(b.password)}}else ph=null;const tags=(Array.isArray(b.tags)?b.tags:[]).slice(0,20).map(v=>plain(v).slice(0,30));const cover=/^\/media\/[a-zA-Z0-9-]+$/.test(b.cover)?b.cover:'';await query(c,'INSERT INTO entries(id,kind,title,body,excerpt,cover,tags,date,status,password_hash,link,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,body=excluded.body,excerpt=excluded.excerpt,cover=excluded.cover,tags=excluded.tags,date=excluded.date,status=excluded.status,password_hash=excluded.password_hash,link=excluded.link,updated_at=excluded.updated_at',id,kind,title||'随手记',body,plain(b.excerpt||body).slice(0,220),cover,JSON.stringify(tags),date,status,ph,safeLink(b.link),old?.created_at||now(),now()).run();return c.json({id,ok:true})}
app.post('/api/admin/entries',saveEntry);app.put('/api/admin/entries/:id',saveEntry);
app.post('/api/admin/entries/:id/archive',async c=>{await query(c,"UPDATE entries SET status='draft',updated_at=? WHERE id=?",now(),c.req.param('id')).run();return c.json({ok:true})});
app.post('/api/admin/media',async c=>{if(!c.env.MEDIA)fail('照片存储尚未开通，请先完成存储配置。',503);const form=await c.req.formData(),file=form.get('file'),entryId=form.get('entry_id')||null;if(!file||typeof file==='string'||file.size>8*1024*1024)fail('请选择不超过8MB的图片。');if(entryId&&!await query(c,'SELECT id FROM entries WHERE id=?',entryId).first())fail('请先保存内容。');const bytes=new Uint8Array(await file.arrayBuffer());let mime='';if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)mime='image/jpeg';if(bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71)mime='image/png';if(new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP')mime='image/webp';if(!mime)fail('只支持 JPG、PNG 和 WebP 图片。');const id=crypto.randomUUID();await c.env.MEDIA.put(id,bytes,{httpMetadata:{contentType:mime}});await query(c,'INSERT INTO media(id,entry_id,mime,size,caption,position,created_at) VALUES(?,?,?,?,?,?,?)',id,entryId,mime,file.size,plain(form.get('caption')).slice(0,300),Date.now(),now()).run();return c.json({id,url:'/media/'+id})});
app.delete('/api/admin/media/:id',c=>deleteMedia(c,query,profile));
app.put('/api/admin/media/:id',async c=>{const b=await data(c);await query(c,'UPDATE media SET caption=? WHERE id=?',plain(b.caption).slice(0,300),c.req.param('id')).run();return c.json({ok:true})});
app.get('/media/:id',async c=>{const id=c.req.param('id'),m=await query(c,'SELECT * FROM media WHERE id=?',id).first();if(!m)fail('照片不存在。',404);const admin=await isAdmin(c);if(!admin){const p=await profile(c);if(m.entry_id){const e=await query(c,'SELECT * FROM entries WHERE id=?',m.entry_id).first();if(!e||e.status!=='published'||!await entryAccess(c,e))fail('照片不可访问。',403)}else if(p.avatar!=='/media/'+id&&!await query(c,"SELECT id FROM poetry_books WHERE cover=? AND status='published'",'/media/'+id).first())fail('照片不可访问。',403)}const o=await c.env.MEDIA.get(id);if(!o)fail('照片不存在。',404);return new Response(o.body,{headers:{'Content-Type':m.mime,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}})});
async function commentsAllowed(c,id){if(!id)return;const e=await visibleEntry(c,id);if(!await entryAccess(c,e))fail('请先解锁文章。',403)}
app.get('/api/comments',async c=>{const id=c.req.query('entry')||null;await commentsAllowed(c,id);return c.json(await all(c,"SELECT id,nickname,message,reply,created_at,replied_at FROM comments WHERE entry_id IS ? AND status='approved' ORDER BY created_at DESC LIMIT 100",id))});
app.post('/api/comments',async c=>{await rate(c,'comment',4,3600000);const b=await data(c);if(b.website)fail('请勿提交垃圾留言。');const id=b.entry_id||null;await commentsAllowed(c,id);const nickname=plain(b.nickname),message=plain(b.message),email=String(b.email||'').trim();if(nickname.length<1||nickname.length>30)fail('昵称须为1–30个字符。');if(message.length<2||message.length>2000)fail('留言须为2–2000个字符。');if(email&&!emailValid(email))fail('邮箱格式不正确。');await query(c,'INSERT INTO comments(id,entry_id,nickname,email,message,created_at) VALUES(?,?,?,?,?,?)',crypto.randomUUID(),id,nickname,email,message,now()).run();return c.json({ok:true,message:'已收到，审核通过后会公开展示。'})});
app.get('/api/admin/comments',async c=>c.json(await all(c,'SELECT c.*,e.title AS entry_title FROM comments c LEFT JOIN entries e ON e.id=c.entry_id ORDER BY c.created_at DESC LIMIT 300')));
app.put('/api/admin/comments/:id',async c=>{const b=await data(c),id=c.req.param('id'),old=await query(c,'SELECT * FROM comments WHERE id=?',id).first();if(!old)fail('留言不存在。',404);const status=['pending','approved','rejected'].includes(b.status)?b.status:old.status,reply=plain(b.reply??old.reply).slice(0,3000);await query(c,'UPDATE comments SET status=?,reply=?,replied_at=? WHERE id=?',status,reply,reply?now():null,id).run();let mail='none';if(status==='approved'&&reply&&reply!==old.reply&&old.email){await query(c,'INSERT INTO mail_outbox(id,comment_id,created_at) VALUES(?,?,?)',crypto.randomUUID(),id,now()).run();mail=await sendMails(c)}return c.json({ok:true,mail})});
async function sendMails(c){if(!c.env.RESEND_API_KEY||!c.env.MAIL_FROM)return 'not-configured';const pending=await all(c,"SELECT o.id,c.email,c.reply,c.entry_id,c.status FROM mail_outbox o JOIN comments c ON c.id=o.comment_id WHERE o.status='pending' LIMIT 20");for(const m of pending){if(m.status!=='approved')continue;const resp=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+c.env.RESEND_API_KEY,'Content-Type':'application/json','Idempotency-Key':m.id},body:JSON.stringify({from:c.env.MAIL_FROM,to:[m.email],subject:'岚山飞文回复了你的留言',text:`你的留言有了新回复：\n\n${m.reply}\n\n在网站查看：${c.env.SITE_ORIGIN}${m.entry_id?'/entry/'+m.entry_id:'/guestbook'}\n\n你收到此邮件，是因为留言时填写了邮箱。`})});if(resp.ok)await query(c,"UPDATE mail_outbox SET status='sent',sent_at=? WHERE id=?",now(),m.id).run();else return 'failed'}return 'sent'}
app.post('/api/admin/mail/retry',async c=>c.json({status:await sendMails(c)}));
app.get('/api/life',async c=>{const year=Math.min(2100,Math.max(2000,Number(c.req.query('year'))||Number(today().slice(0,4))));const admin=await isAdmin(c);const activities=await all(c,`SELECT * FROM activities ${admin?'':'WHERE private=0'} ORDER BY position`);const checks=await all(c,`SELECT activity_id,date FROM checkins JOIN activities ON activities.id=checkins.activity_id WHERE date>=? AND date<=? ${admin?'':'AND activities.private=0'}`,year+'-01-01',year+'-12-31');return c.json({year,activities,checks,today:today(),admin})});
app.post('/api/admin/activities',async c=>{const b=await data(c),name=plain(b.name).slice(0,20);if(!name)fail('请填写活动名称。');const count=(await query(c,'SELECT COUNT(*) AS n FROM activities').first()).n;if(count>=16)fail('最多支持16个活动类别。');const id=crypto.randomUUID();await query(c,'INSERT INTO activities(id,name,icon,color,private,position) VALUES(?,?,?,?,?,?)',id,name,plain(b.icon).slice(0,8)||'○',/^#[\da-fA-F]{6}$/.test(b.color)?b.color:'#8c9c80',b.private?1:0,count).run();return c.json({id})});
app.put('/api/admin/activities/:id',async c=>{const b=await data(c);if(!plain(b.name))fail('请填写活动名称。');await query(c,'UPDATE activities SET name=?,icon=?,color=?,private=? WHERE id=?',plain(b.name).slice(0,20),plain(b.icon).slice(0,8)||'○',/^#[\da-fA-F]{6}$/.test(b.color)?b.color:'#8c9c80',b.private?1:0,c.req.param('id')).run();return c.json({ok:true})});
app.post('/api/admin/checkins',async c=>{const b=await data(c);if(!validDate(b.date)||b.date>today())fail('请选择今天或过去的有效日期。');if(!await query(c,'SELECT id FROM activities WHERE id=?',b.activity_id).first())fail('活动不存在。');await query(c,'INSERT OR IGNORE INTO checkins(activity_id,date,created_at) VALUES(?,?,?)',b.activity_id,b.date,now()).run();return c.json({ok:true})});
async function bgmFetch(c,key,url,ttl=900000){const cached=await query(c,'SELECT * FROM cache WHERE key=?',key).first();if(cached&&cached.expires_at>Date.now())return {...JSON.parse(cached.value),stale:false};try{const r=await fetch(url,{headers:{'User-Agent':'LanshanFeiwen/1.0 (https://lsfw.top)'},signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error('upstream');const value=await r.json(),out={data:value,syncedAt:now()};await query(c,'INSERT INTO cache(key,value,expires_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,expires_at=excluded.expires_at',key,JSON.stringify(out),Date.now()+ttl).run();return out}catch{if(cached)return {...JSON.parse(cached.value),stale:true};fail('Bangumi 暂时无法连接，请稍后再试。',502)}}
app.get('/steam',c=>c.text('此页面已移除。',410));
app.get('/steam.js',c=>c.text('此页面已移除。',410));
app.get('/api/bangumi/profile',async c=>c.json(await bgmFetch(c,'bgm:profile','https://api.bgm.tv/v0/users/'+c.env.BANGUMI_USER)));
app.get('/api/bangumi/collections',async c=>{const type=Math.min(5,Math.max(1,Number(c.req.query('type'))||3)),subject=Math.min(6,Math.max(1,Number(c.req.query('subject'))||2)),offset=Math.min(10000,Math.max(0,Number(c.req.query('offset'))||0));const out=await bgmFetch(c,`bgm:${subject}:${type}:${offset}`,`https://api.bgm.tv/v0/users/${c.env.BANGUMI_USER}/collections?subject_type=${subject}&type=${type}&limit=24&offset=${offset}`);out.data.data=out.data.data.filter(x=>!x.private).map(x=>({subject_id:x.subject_id,type:x.type,rate:x.rate,comment:x.comment,tags:x.tags,ep_status:x.ep_status,updated_at:x.updated_at,subject:{name:x.subject.name_cn||x.subject.name,image:x.subject.images?.common,eps:x.subject.eps}}));return c.json(out)});
app.get('/api/bangumi/timeline',async c=>{const until=String(c.req.query('until')||'');if(until&&!/^\d+$/.test(until))fail('分页参数无效。');return c.json(await bgmFetch(c,'bgm:timeline:'+until,`https://next.bgm.tv/p1/users/${c.env.BANGUMI_USER}/timeline?limit=20${until?'&until='+until:''}`))});
app.get('/api/admin/export',async c=>{const tables=['settings','entries','media','comments','activities','checkins','poetry_books','poems','food_records'];const result={exported_at:now(),version:1};for(const t of tables)result[t]=await all(c,`SELECT * FROM ${t}`);return c.json(result)});
app.get('*',async c=>{if(c.req.path.startsWith('/api/'))return c.json({error:'接口不存在。'},404);if(c.req.path==='/robots.txt')return c.text('User-agent: *\nDisallow: /admin\nDisallow: /api/\n');const url=new URL(c.req.url);if(c.req.path==='/admin'||c.req.path.startsWith('/admin/'))url.pathname='/admin.html';else if(!/\.[a-z0-9]+$/i.test(c.req.path))url.pathname='/index.html';const r=await c.env.ASSETS.fetch(new Request(url,c.req.raw));return new Response(r.body,r)});
export default app;
